In [0]:
#NUMPY

In [2]:
a=5
b=7
x=sum(x)
print(a+b)

12

In [3]:
num1 = 10
num2 = 14
num3 = 12
if (num1 >= num2) and (num1 >= num3):
   largest = num1
elif (num2 >= num1) and (num2 >= num3):
   largest = num2
else:
   largest = num3
print("The largest number between",num1,",",num2,"and",num3,"is",largest)

The largest number between 10 , 14 and 12 is 14

In [0]:
lis=[9,5,6]
max=0
for i in lis

In [9]:
x,y=0,1

while y<15:
    print(y)
    x,y = y,x+y

1
1
2
3
5
8
13

In [0]:
import numpy as np

In [3]:
vector_row = np.array([1, 2, 3])
vector_row

array([1, 2, 3])

In [0]:
a = np.random.randn(3, 3)

In [7]:
a

array([[ 0.28026033, -0.43453875,  0.16849286],
       [ 1.5045294 ,  0.59296586, -1.21273533],
       [-1.41431498, -0.08832584, -0.51338094]])

In [0]:
b=np.random.randn(3, 3)

In [11]:
b

array([[-0.25941769, -0.64748362, -0.02481609],
       [ 0.5449152 , -2.61223578, -1.6492695 ],
       [-1.14809332,  1.12536754,  1.0171454 ]])

In [12]:
np.dot(a, b)

array([[ 0.39535884, -2.23958002, -1.39510139],
       [-0.67956647, -0.76864495, -0.06262499],
       [-1.63223088,  1.28901853,  1.33808703]])

In [0]:
a = np.random.randint (low=2, high=4,size=(3, 3))

In [15]:
a

array([[3, 2, 3],
       [2, 2, 2],
       [3, 2, 3]])

In [0]:
b = np.random.randint (low=1, high=3,size=(3, 3))

In [17]:
b

array([[2, 2, 1],
       [2, 2, 1],
       [2, 2, 1]])

In [18]:
np.dot(a, b)

array([[16, 16,  8],
       [12, 12,  6],
       [16, 16,  8]])

In [19]:
np.cross(a, b)

array([[-4,  3,  2],
       [-2,  2,  0],
       [-4,  3,  2]])

In [0]:
import pandas as pd

In [0]:
iris=pd.read_csv("iris.csv")

In [4]:
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
6             4.6          3.4           1.4          0.3     setosa
7             5.0          3.4           1.5          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
9             4.9          3.1           1.5          0.1     setosa
10            5.4          3.7           1.5          0.2     setosa
11            4.8          3.4           1.6          0.2     setosa
12            4.8          3.0           1.4          0.1     setosa
13            4.3          3.0           1.1          0.1     setosa
14            5.8          4.0           1.2          0.2     setosa
15            5.7          4.4           1.5          0.4     setosa
16            5.4          3.9           1.3          0.4     setosa
17            5.1          3.5           1.4          0.3     setosa
18            5.7          3.8           1.7          0.3     setosa
19            5.1          3.8           1.5          0.3     setosa
20            5.4          3.4           1.7          0.2     setosa
21            5.1          3.7           1.5          0.4     setosa
22            4.6          3.6           1.0          0.2     setosa
23            5.1          3.3           1.7          0.5     setosa
24            4.8          3.4           1.9          0.2     setosa
25            5.0          3.0           1.6          0.2     setosa
26            5.0          3.4           1.6          0.4     setosa
27            5.2          3.5           1.5          0.2     setosa
28            5.2          3.4           1.4          0.2     setosa
29            4.7          3.2           1.6          0.2     setosa
..            ...          ...           ...          ...        ...
120           6.9          3.2           5.7          2.3  virginica
121           5.6          2.8           4.9          2.0  virginica
122           7.7          2.8           6.7          2.0  virginica
123           6.3          2.7           4.9          1.8  virginica
124           6.7          3.3           5.7          2.1  virginica
125           7.2          3.2           6.0          1.8  virginica
126           6.2          2.8           4.8          1.8  virginica
127           6.1          3.0           4.9          1.8  virginica
128           6.4          2.8           5.6          2.1  virginica
129           7.2          3.0           5.8          1.6  virginica
130           7.4          2.8           6.1          1.9  virginica
131           7.9          3.8           6.4          2.0  virginica
132           6.4          2.8           5.6          2.2  virginica
133           6.3          2.8           5.1          1.5  virginica
134           6.1          2.6           5.6          1.4  virginica
135           7.7          3.0           6.1          2.3  virginica
136           6.3          3.4           5.6          2.4  virginica
137           6.4          3.1           5.5          1.8  virginica
138           6.0          3.0           4.8          1.8  virginica
139           6.9          3.1           5.4          2.1  virginica
140           6.7          3.1           5.6          2.4  virginica
141           6.9          3.1           5.1          2.3  virginica
142           5.8          2.7           5.1          1.9  virginica
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [0]:
df=iris.head(5)

In [7]:
df

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [8]:
pd.isnull(df)

   sepal_length  sepal_width  petal_length  petal_width  species
0         False        False         False        False    False
1         False        False         False        False    False
2         False        False         False        False    False
3         False        False         False        False    False
4         False        False         False        False    False

In [9]:
pd.notnull(df)

   sepal_length  sepal_width  petal_length  petal_width  species
0          True         True          True         True     True
1          True         True          True         True     True
2          True         True          True         True     True
3          True         True          True         True     True
4          True         True          True         True     True

In [0]:
import pandas as pd

In [0]:
df2=pd.read_csv("diabetes.csv")

In [5]:
df2

      6  148  72  35    0  33.6  0.627  50  1
0     1   85  66  29    0  26.6  0.351  31  0
1     8  183  64   0    0  23.3  0.672  32  1
2     1   89  66  23   94  28.1  0.167  21  0
3     0  137  40  35  168  43.1  2.288  33  1
4     5  116  74   0    0  25.6  0.201  30  0
5     3   78  50  32   88  31.0  0.248  26  1
6    10  115   0   0    0  35.3  0.134  29  0
7     2  197  70  45  543  30.5  0.158  53  1
8     8  125  96   0    0   0.0  0.232  54  1
9     4  110  92   0    0  37.6  0.191  30  0
10   10  168  74   0    0  38.0  0.537  34  1
11   10  139  80   0    0  27.1  1.441  57  0
12    1  189  60  23  846  30.1  0.398  59  1
13    5  166  72  19  175  25.8  0.587  51  1
14    7  100   0   0    0  30.0  0.484  32  1
15    0  118  84  47  230  45.8  0.551  31  1
16    7  107  74   0    0  29.6  0.254  31  1
17    1  103  30  38   83  43.3  0.183  33  0
18    1  115  70  30   96  34.6  0.529  32  1
19    3  126  88  41  235  39.3  0.704  27  0
20    8   99  84   0    0  35.4  0.388  50  0
21    7  196  90   0    0  39.8  0.451  41  1
22    9  119  80  35    0  29.0  0.263  29  1
23   11  143  94  33  146  36.6  0.254  51  1
24   10  125  70  26  115  31.1  0.205  41  1
25    7  147  76   0    0  39.4  0.257  43  1
26    1   97  66  15  140  23.2  0.487  22  0
27   13  145  82  19  110  22.2  0.245  57  0
28    5  117  92   0    0  34.1  0.337  38  0
29    5  109  75  26    0  36.0  0.546  60  0
..   ..  ...  ..  ..  ...   ...    ...  .. ..
737   2   99  60  17  160  36.6  0.453  21  0
738   1  102  74   0    0  39.5  0.293  42  1
739  11  120  80  37  150  42.3  0.785  48  1
740   3  102  44  20   94  30.8  0.400  26  0
741   1  109  58  18  116  28.5  0.219  22  0
742   9  140  94   0    0  32.7  0.734  45  1
743  13  153  88  37  140  40.6  1.174  39  0
744  12  100  84  33  105  30.0  0.488  46  0
745   1  147  94  41    0  49.3  0.358  27  1
746   1   81  74  41   57  46.3  1.096  32  0
747   3  187  70  22  200  36.4  0.408  36  1
748   6  162  62   0    0  24.3  0.178  50  1
749   4  136  70   0    0  31.2  1.182  22  1
750   1  121  78  39   74  39.0  0.261  28  0
751   3  108  62  24    0  26.0  0.223  25  0
752   0  181  88  44  510  43.3  0.222  26  1
753   8  154  78  32    0  32.4  0.443  45  1
754   1  128  88  39  110  36.5  1.057  37  1
755   7  137  90  41    0  32.0  0.391  39  0
756   0  123  72   0    0  36.3  0.258  52  1
757   1  106  76   0    0  37.5  0.197  26  0
758   6  190  92   0    0  35.5  0.278  66  1
759   2   88  58  26   16  28.4  0.766  22  0
760   9  170  74  31    0  44.0  0.403  43  1
761   9   89  62   0    0  22.5  0.142  33  0
762  10  101  76  48  180  32.9  0.171  63  0
763   2  122  70  27    0  36.8  0.340  27  0
764   5  121  72  23  112  26.2  0.245  30  0
765   1  126  60   0    0  30.1  0.349  47  1
766   1   93  70  31    0  30.4  0.315  23  0

[767 rows x 9 columns]

In [7]:
pd.isnull(df2)

         6    148     72     35      0   33.6  0.627     50      1
0    False  False  False  False  False  False  False  False  False
1    False  False  False  False  False  False  False  False  False
2    False  False  False  False  False  False  False  False  False
3    False  False  False  False  False  False  False  False  False
4    False  False  False  False  False  False  False  False  False
5    False  False  False  False  False  False  False  False  False
6    False  False  False  False  False  False  False  False  False
7    False  False  False  False  False  False  False  False  False
8    False  False  False  False  False  False  False  False  False
9    False  False  False  False  False  False  False  False  False
10   False  False  False  False  False  False  False  False  False
11   False  False  False  False  False  False  False  False  False
12   False  False  False  False  False  False  False  False  False
13   False  False  False  False  False  False  False  False  False
14   False  False  False  False  False  False  False  False  False
15   False  False  False  False  False  False  False  False  False
16   False  False  False  False  False  False  False  False  False
17   False  False  False  False  False  False  False  False  False
18   False  False  False  False  False  False  False  False  False
19   False  False  False  False  False  False  False  False  False
20   False  False  False  False  False  False  False  False  False
21   False  False  False  False  False  False  False  False  False
22   False  False  False  False  False  False  False  False  False
23   False  False  False  False  False  False  False  False  False
24   False  False  False  False  False  False  False  False  False
25   False  False  False  False  False  False  False  False  False
26   False  False  False  False  False  False  False  False  False
27   False  False  False  False  False  False  False  False  False
28   False  False  False  False  False  False  False  False  False
29   False  False  False  False  False  False  False  False  False
..     ...    ...    ...    ...    ...    ...    ...    ...    ...
737  False  False  False  False  False  False  False  False  False
738  False  False  False  False  False  False  False  False  False
739  False  False  False  False  False  False  False  False  False
740  False  False  False  False  False  False  False  False  False
741  False  False  False  False  False  False  False  False  False
742  False  False  False  False  False  False  False  False  False
743  False  False  False  False  False  False  False  False  False
744  False  False  False  False  False  False  False  False  False
745  False  False  False  False  False  False  False  False  False
746  False  False  False  False  False  False  False  False  False
747  False  False  False  False  False  False  False  False  False
748  False  False  False  False  False  False  False  False  False
749  False  False  False  False  False  False  False  False  False
750  False  False  False  False  False  False  False  False  False
751  False  False  False  False  False  False  False  False  False
752  False  False  False  False  False  False  False  False  False
753  False  False  False  False  False  False  False  False  False
754  False  False  False  False  False  False  False  False  False
755  False  False  False  False  False  False  False  False  False
756  False  False  False  False  False  False  False  False  False
757  False  False  False  False  False  False  False  False  False
758  False  False  False  False  False  False  False  False  False
759  False  False  False  False  False  False  False  False  False
760  False  False  False  False  False  False  False  False  False
761  False  False  False  False  False  False  False  False  False
762  False  False  False  False  False  False  False  False  False
763  False  False  False  False  False  False  False  False  False
764  False  False  False  False  False  False  False  False  False
765  False  False  False  False  False  False  False  False  False
766  False  False  False  False  False  False  False  False  False

[767 rows x 9 columns]

In [0]:
import pandas as pd

In [0]:

data = pd.read_csv("dmarks.csv")

In [32]:
data

  rollno\tphysics\tchemistry\tbiology\tmaths\tsst
0                            0\t6\t148\t72\t35\t0
1                              1\t1\t85\t66\t29\t
2                              2\t8\t183\t64\t0\t
3                            3\t1\t89\t66\t23\t94
4                          4\t0\t137\t40\t35\t168
5                               5\t5\t116\t74\t\t
6                            6\t3\t78\t50\t32\t88
7                               7\t10\t115\t\t\t0
8                          8\t2\t197\t70\t45\t543
9                               9\t8\t125\t96\t\t